//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication12.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class fuck
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Required")]
        public string firstname { get; set; }
        [Required(ErrorMessage = "Required")]
        public string lastname { get; set; }
        [Required(ErrorMessage = "Required")]
        public int age { get; set; }
        [Required(ErrorMessage = "Required")]
        public string gender { get; set; }
        [Required(ErrorMessage = "Required")]
        [RegularExpression(@"^[\w\.\+\#]{3,}[@][a-z A-z]{3,}[\.][a-zA-Z]{3,}$",ErrorMessage ="Syntx Error")]
        public string email { get; set; }
        [Required(ErrorMessage = "Required")]
        [RegularExpression(@"(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$", ErrorMessage = "Syntx Error")]
        public string password { get; set; }
        [Required(ErrorMessage = "Required")]
        [Compare("password",ErrorMessage ="Password donot match")]
        public string cpassword { get; set; }

    }
}
